apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-repo
  namespace: flux-system
spec:
  interval: 1m
  timeout: 1m
  ref:
    branch: REPLACE_ME_GIT_BRANCH
  url: https://github.com/REPLACE_ME/REPLACE_ME

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  path: ./gitops/apps/sample-app/overlays/cluster-a
